name: automerge
on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened, ready_for_review, unlocked]
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  status: {}
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge all eligible PRs from exercism-solutions-syncer
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          AUTOCLOSE: "true"
          MERGE_FILTER_AUTHOR: app/exercism-solutions-syncer
          MERGE_LABELS: ""
          LOG: "TRACE"
