name: Sweep & Merge Exercism Sync PRs

on:
  schedule:
    - cron: '0 13 * * *'   # daily at 13:00 UTC (09:00 ET)
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  sweep:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.repository }} # e.g. nhdewitt/exercism-solutions

    steps:
      - name: Sanity — list open PRs (author, title)
        run: >
          gh pr list --repo "$REPO" --state open --limit 200
          --json number,author,title
          -q '.[] | "\(.number)\t\(.author.login)\t\(.title)"'

      - name: Merge App-authored PRs (squash + delete branch)
        run: |
          set -euo pipefail
          prs=$(gh pr list --repo "$REPO" \
                 --search 'is:open is:pr author:app/exercism-solutions-syncer' \
                 --limit 200 \
                 --json number -q '.[].number')
          if [ -z "$prs" ]; then
            echo "No open PRs from app/exercism-solutions-syncer."
            exit 0
          fi

          for n in $prs; do
            echo "Merging #$n (squash)…"
            gh pr merge "$n" --repo "$REPO" --squash --delete-branch
          done
